//**************************************
// Generated by mcpp translator
// Version 1.3
//**************************************

#ifndef __ISCA_CTRL_TRANS_M_H__
#define __ISCA_CTRL_TRANS_M_H__

#include"mcode/mvector.h"
#include"mcode/mstring.h"
#include"mcode/mstream.h"
#include"mcode/mclient.h"


struct TransData
{
	MLang::Long	create_time;
	int	file_type;
	int	interval_type;
	void __write(MLang::OutputStream&__os)const;
	void __read(MLang::InputStream&__is);
};
typedef MLang::VECTOR<TransData> TransData_SEQ;
struct CtrlTransPkg
{
	int	data_num;
	TransData_SEQ	data_info_seq;
	CtrlTransPkg();
	CtrlTransPkg(const CtrlTransPkg&);
	CtrlTransPkg&operator=(const CtrlTransPkg&);
	void __write(MLang::OutputStream&__os)const;
	void __read(MLang::InputStream&__is);
};
#endif
